# Generated by Django 2.0.7 on 2018-08-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='position',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
