# Generated by Django 2.0.7 on 2018-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180803_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='price_purchased_usd',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=10),
        ),
    ]
