# Generated by Django 2.0.7 on 2018-08-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20180807_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=17),
        ),
    ]
