# Generated by Django 2.0.7 on 2018-08-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20180807_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_purchased',
            field=models.DateTimeField(),
        ),
    ]
