# Generated by Django 2.0.7 on 2018-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20180807_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
